---

- name: Include os specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
  tags:
    - 'role::ntp'
    - 'role::ntp:install'
    - 'role::ntp:config'

- name: Importing tasks from installation.yml
  ansible.builtin.import_tasks: installation.yml

- name: Importing tasks from configuration.yml
  ansible.builtin.import_tasks: configuration.yml
